### ISSUE TITLE
It doesn't show in the share menu on Android

### ISSUE THREAD

**Issue by MrPropre** [schlagmichdoch/PairDrop#11]
It doesn't show even if I want to share a link or a text. I use Microsoft Edge for Windows and Android.

**Comment by schlagmichdoch** [comment]
Thanks for testing it out! Could you do some more testing?
- Does Snapdrop (https://snapdrop.net) appear in the share menu after installation when sharing a link or is this only failing to work with PairDrop?
- Please try out this demo app, install it as pwa and check wether you can share a link with it from the share-menu:
  - https://web-share-tar.glitch.me/
- Please try out these demo apps, install them as PWAs and check whether you can share a file with them from the share-menu:
  - https://mconverter.eu/ 
  - https://scrapbook-pwa.web.app/

Do you know of any other PWAs where sharing files directly from the share-menu works?

---
For Edge on Windows there is another Api implemented which works really well: [How-To](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/how-to.md#share-files-directly-form-context-menu-on-windows)

**Comment by MrPropre** [comment]
It seems that web share target api isn't working on Edge for Android, none of the apps I installed are showed in the share menu. I tried with Chrome for Android and it's showing.

On Windows there is a native share menu similar to Android. You can use it to send emails, to use windows share feature or to share with compatible apps. On Edge, Snapdrop, Mconverter and Scrapbook are displayed on the menu, but not PairDrop. I tried with Google Chrome and it doesn't seem to be compatible with the Windows native share menu, idk why.

So, for Android/Chrome, when I share a photo with pairdrop, the website goes down : ERR_FAILED

**Comment by schlagmichdoch** [comment]
The Api only works together with the platform the browser is hosted on: [caniuse.com](https://caniuse.com/?search=share_target)
- Android -> Chrome for Android
- Windows -> Edge for Windows
- Chrome OS -> (probably) Chrome for Desktop

So you are saying on after installing Snapdrop with Edge for Windows it is shown in the Windows share menu but PairDrop isn't?

I've rewritten some server-worker logic. Can you please reinstall the PWA and try again?
- Can you see PairDrop in Androids native share menu after installing it via Chrome for Android?
- Can you share a link with it?
- Can you share a file with it?
- What's the complete Error message you get?

**Comment by MrPropre** [comment]
Maybe I messed up with something on my Windows but PairDrop still doesn't show in the share menu.

With my Android:

https://user-images.githubusercontent.com/36234981/214151681-0b1eab6f-6f20-4fc7-89c0-e43b5a6fb5a1.mp4

**Comment by schlagmichdoch** [comment]
Thanks for testing! I will take a look at it, as soon as I get my hands on an Android device for testing.

For me, none of the mentioned apps are shown in windows share menu though.

It is however possible to send files with PairDrop on windows via the context menu with "open with > PairDrop" or "send to > PairDrop". You will find a guide here:
https://github.com/schlagmichdoch/PairDrop/blob/master/docs/how-to.md#share-files-directly-form-context-menu-on-windows

**Comment by schlagmichdoch** [comment]
@MrPropre There is now a fix in `v1.5.2` running live at https://pairdrop.net/

Does this close your issue?

**Comment by schlagmichdoch** [comment]
That’s weird. Is this behavior the same after reinstalling snapdrop and pairdrop? For me both are not shown at all when installing as PWA via Edge. Maybe this is still under development and only allows GET requests or something alike.. 

I guess this is an edge case though and this issue can safely be closed. IMO the important thing is that it works on Android.

**Comment by schlagmichdoch** [comment]
Alright, then I will close this for now. Thanks for the quick response!

 If someone really needs the share menu on Edge please create a new issue.

**Comment by MrPropre** [comment]
I tried reinstalling both and Snapdrop is still the only one being displayed. You are right maybe it is still under development but I tried with Mconverter and it is displayed so I'm not sure if it's a problem with GET requests

Also, it seems to me that sharing on iOS using your custom Shortcut doesn't work with Photos app. However it work through Files app. I use iOS 15.7.3 on iPhone SE (1st gen)

**Comment by schlagmichdoch** [comment]
Do you use the latest version?

https://routinehub.co/shortcut/13990/

Sharing from the photos app works for me. What exactly happens when you share a photo?

**Comment by MrPropre** [comment]
Sorry I forgot this thread. I have the same problem : https://www.reddit.com/r/shortcuts/comments/uqbnlt/the_file_cannot_be_opened_because_you_dont_have/

**Comment by MrPropre** [comment]
https://user-images.githubusercontent.com/36234981/235321019-03601f7a-6a7c-4f73-873c-192e4233bf73.mp4

**Comment by schlagmichdoch** [comment]
Please create a new issue as this has nothing todo with this issue.
Anyways, I would try to reset the privacy settings of the shortcut or deleting and redownloading the shortcut.
If the problem persists, create a new issue and I will look into it.

**Comment by schlagmichdoch** [comment]
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](#284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---
Thanks for testing it out! Could you do some more testing?
- Does Snapdrop (https://snapdrop.net) appear in the share menu after installation when sharing a link or is this only failing to work with PairDrop?
- Please try out this demo app, install it as pwa and check wether you can share a link with it from the share-menu:
  - https://web-share-tar.glitch.me/
- Please try out these demo apps, install them as PWAs and check whether you can share a file with them from the share-menu:
  - https://mconverter.eu/ 
  - https://scrapbook-pwa.web.app/

Do you know of any other PWAs where sharing files directly from the share-menu works?

---
For Edge on Windows there is another Api implemented which works really well: [How-To](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/how-to.md#share-files-directly-form-context-menu-on-windows)

Comment by @schlagmichdoch:
---

The Api only works together with the platform the browser is hosted on: [caniuse.com](https://caniuse.com/?search=share_target)
- Android -> Chrome for Android
- Windows -> Edge for Windows
- Chrome OS -> (probably) Chrome for Desktop

So you are saying on after installing Snapdrop with Edge for Windows it is shown in the Windows share menu but PairDrop isn't?

I've rewritten some server-worker logic. Can you please reinstall the PWA and try again?
- Can you see PairDrop in Androids native share menu after installing it via Chrome for Android?
- Can you share a link with it?
- Can you share a file with it?
- What's the complete Error message you get?
