### ISSUE TITLE
Enhancement: Text Formatting

### ISSUE THREAD

**Issue by markaldridge** [schlagmichdoch/PairDrop#112]
Text formatting is lost when the text is copied from the receiving end.
I want to be able to send PowerShell code for example between devices and keep the formatting intact.

**Comment by schlagmichdoch** [comment]
I’m not sure what you mean exactly. Please provide an example:
- originally sent text
- received text (current behavior)
- received text (expected behavior)

**Comment by markaldridge** [comment]
- originally sent text
param (
    [switch] $Check = $False
)

- received text (current behavior)
param (    [switch] $Check = $False)

- received text (expected behavior)
param (
    [switch] $Check = $False
)

Here's some images, https://postimg.cc/gallery/rpDrgYR

**Comment by schlagmichdoch** [comment]
Thanks for the example!

This is fixed in `v1.7.4` and live on pairdrop.net

It needed a simple replacement of ` HTMLElement.innerText` to `node.textContent`. Additionally to the differences listed [here](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innertext) innerText strips the content of all linebreaks while textContent leaves them in.

Does this now work for you too?

**Comment by markaldridge** [comment]
The formatting looks to be working correctly now.
I do notice that when I have VS Code set to PowerShell it shows the
copied indentations as yellow boxes.
If I copy several 100 lines of PowerShell code, I get message saying "This
document contains many invisible unicode characters"

https://postimg.cc/gallery/DFvZQ2B

Image 1: Shows when I hover my mouse over the unicode character
Image 2: Shows VS Code disapplying the unicode characters as yellow boxes
Image 3: Shows how the code should appear once received and copied into VS
Code
Image 4: Shows when I send 500 lines of PowerShell code via pairdrop, paste
into VS Code and the warning that's displayed

**Comment by schlagmichdoch** [comment]
So that's weird. Apparently, browsers fiddle around with content when it is pasted so that two spaces `  ` become one NO-BREAK Space ([U+00A0 / \&nbsp;](https://www.fileformat.info/info/unicode/char/00a0/index.htm)) and one normal space `  `.

Could you please test whether the patch on this instance works for you: https://pairdrop-dev.onrender.com/

Alternatively, you have the possibility to paste your text *before* selecting a peer and send it directly by selecting a peer afterwords. For me, that way the problem does not occur. This does not work on Firefox though..
