### ISSUE TITLE
Check compatibility with the app Snapdrop for Android

### ISSUE THREAD

**Issue by schlagmichdoch** [schlagmichdoch/PairDrop#19]
Test whether PairDrop is compatible with the snapdrop android app: https://play.google.com/store/apps/details?id=com.fmsys.snapdrop

If yes, add it to the FAQ

**Comment by schlagmichdoch** [comment]
Corresponding issue on snapdrop-android repository https://github.com/fm-sys/snapdrop-android/issues/246#issue-1567014062

**Comment by xundeenergie** [comment]
The Pairing does not work now, because Snapdrop for Android hat not possibility to pair devices...

I tried it on my second phone again... run an original snapdrop-container on the same domain, then connect from Snapdrop for android, and then stop the original snapdrop-container and start pairdrop-container... sharing works perfectly in the same lan/wlan. Even sharing pictures from gallery via Share-Button and choosing SnapDrop-App.

**Comment by schlagmichdoch** [comment]
Thanks for testing!
Sending works fine on the app but receiving is still an issue, as the PairDrop sends multiple files at once. I'll ask the creator of the App how we should proceed.
