### ISSUE TITLE
[Enhancement]Use an API call for opening pairing menu.

### ISSUE THREAD

**Issue by TheBossMan3** [schlagmichdoch/PairDrop#207]
I am а shortcut developer that uses PairDrop for its sharing functionality. I would like to know if there was а way to (or if you could) make there be а way to show the pairing menu for being able to see the pairing code

**Comment by schlagmichdoch** [comment]
Not sure what you mean. Are you talking about iOS Shortcuts? 

What exactly are you trying to achieve? Do you simply want to open PairDrop with the pairing dialog opened?
Or do you want to make some kind of API call to the backend to receive a pairing code and a pairing secret and a peer id?

**Comment by TheBossMan3** [comment]
I right now have а way for it to pair. I was just wondering if there was а way to do like а https://pairdrop.net/?pair and have it open the pairing menu

**Comment by schlagmichdoch** [comment]
There is already the possibility to "accept" a pairing initiation via the link behind the QR-code (or via click on the QR-code) which looks like this: https://pairdrop.net/?pair_key=948302

Also, there is the possibility to enter a public room via an URL like this: https://pairdrop.net/?room_id=qgkjq

For either URL to work, the room and the pair key must exist and be valid though.

I can imagine opening the dialogs via URL argument like so https://pairdrop.net/?init=pair and https://pairdrop.net/?init=room in order to open. Would that be sufficient?

**Comment by TheBossMan3** [comment]
Yes, that would be sufficient. Thank you for all of your hard work on PairDrop

**Comment by schlagmichdoch** [comment]
This is implemented in `v1.10.0`.

You can now initiate pairing and public rooms via ?init=pair_ and _?init=public_room_ accordingly.

**Comment by schlagmichdoch** [comment]
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

Not sure what you mean. Are you talking about iOS Shortcuts? 

What exactly are you trying to achieve? Do you simply want to open PairDrop with the pairing dialog opened?
Or do you want to make some kind of API call to the backend to receive a pairing code and a pairing secret and a peer id?

Comment by @schlagmichdoch:
---

There is already the possibility to "accept" a pairing initiation via the link behind the QR-code (or via click on the QR-code) which looks like this: https://pairdrop.net/?pair_key=948302

Also, there is the possibility to enter a public room via URL like this: https://pairdrop.net/?room_id=qgkjq

For either URL to work, the room and the pair key must exist and be valid though.

I can imagine opening the dialogs via URL argument like so https://pairdrop.net/?init=pair and https://pairdrop.net/?init=room in order to open. Would that be sufficient?
