### ISSUE TITLE
[Bug] Unable to rename the Pairdrop instance in Firefox for Windows

### ISSUE THREAD

**Issue by nesper8** [schlagmichdoch/PairDrop#219]
**Describe the bug**
The user is not able to rename the Pairdrop instance when using Firefox for Windows

**To Reproduce**
1. Open Pairdrop on Firefox for Windows
2. Try renaming the Pairdrop instance
3. See error

**Expected behavior**
Able to rename the Pairdrop instance

**Screenshots**
https://github.com/schlagmichdoch/PairDrop/assets/57890520/af304b17-8a39-49dc-b2a4-dfff249b7447

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 v19044.3693
 - Browser: Firefox 
 - Version: v120.0.1

**Bug occurs on official PairDrop instance https://pairdrop.net/**
Yes
Version: v1.9.4

**Bug occurs on self-hosted PairDrop instance**
No

**Comment by schlagmichdoch** [comment]
Hi @nesper8,
Thanks for reporting!

This might be due to a rollback I had to do yesterday as I faced a problem during deployment. I’ll get back to you, when that’s fixed.

What _error_ are you referring too? What does the browser console say?

**Comment by schlagmichdoch** [comment]
> This might be due to a rollback I had to do yesterday as I faced a problem during deployment. I’ll get back to you, when that’s fixed.

This is since fixed and PairDrop now runs at version `v1.10.1` on the server. Do you still have this issue?

**Comment by schlagmichdoch** [comment]
I cannot reproduce this on Firefox for Windows. You simply have to click on the displayed name and edit with your keyboard.

**Comment by TheNexter** [comment]
Hello men, same problem :
Ubuntu 23.10
Firefox 120.0.1

Log in console :
![Capture d’écran du 2023-12-14 12-27-05](https://github.com/schlagmichdoch/PairDrop/assets/17613028/9b0a217e-f33f-45e6-9327-9f625874e5b8)

Log in text format :
`WS receive: unknown message type 
Object { type: "ws-config", wsConfig: {…} }
network.js:162:25
    _onMessage https://pairdrop.net/scripts/network.js:162
    onmessage https://pairdrop.net/scripts/network.js:50
    (Asynchrone : EventHandlerNonNull)
    _connect https://pairdrop.net/scripts/network.js:50
    ServerConnection https://pairdrop.net/scripts/network.js:18
    PairDrop https://pairdrop.net/scripts/ui.js:2792
    fire https://pairdrop.net/scripts/network.js:1179
    Localization https://pairdrop.net/scripts/localization.js:21
    (Asynchrone : promise callback)
    Localization https://pairdrop.net/scripts/localization.js:19
    <anonyme> https://pairdrop.net/scripts/ui.js:2818
`

`Uncaught TypeError: msg.message is undefined
    _onDisplayName https://pairdrop.net/scripts/network.js:178
    _onMessage https://pairdrop.net/scripts/network.js:129
    onmessage https://pairdrop.net/scripts/network.js:50
    _connect https://pairdrop.net/scripts/network.js:50
    ServerConnection https://pairdrop.net/scripts/network.js:18
    PairDrop https://pairdrop.net/scripts/ui.js:2792
    fire https://pairdrop.net/scripts/network.js:1179
    Localization https://pairdrop.net/scripts/localization.js:21
    promise callback*Localization https://pairdrop.net/scripts/localization.js:19
    <anonymous> https://pairdrop.net/scripts/ui.js:2818
network.js:178:43
`

**Comment by schlagmichdoch** [comment]
Thanks for the logs @TheNexter

This is due to the PairDrop version having been updated yesterday which now does not work with the old version still running in your browser. 
To solve this you only need to close all open PairDrop tabs. Only then the service worker / browser will update the cached files in the background and everything should work smoothly again.

Could you please that and report back whether it worked?

**Comment by schlagmichdoch** [comment]
Is this still an issue @nesper8 @TheNexter ?

**Comment by nesper8** [comment]
the issue has been fixed
i was pre-occupied with testing ROMs for my phone 
sorry for not closing on time

**Comment by TheNexter** [comment]
Hello, sorry, yes working great now ;)

**Comment by schlagmichdoch** [comment]
Great! Thanks for reporting back! :)

**Comment by schlagmichdoch** [comment]
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

> This might be due to a rollback I had to do yesterday as I faced a problem during deployment. I’ll get back to you, when that’s fixed.

This is since fixed and PairDrop now runs at version `v1.10.1` on the server. Do you still have this issue?

Comment by @schlagmichdoch:
---

Thanks for the logs @TheNexter

This is due to the PairDrop instance running on pairdrop.net has been updated yesterday which now does not work with the old version still running in your browser. 
To solve this you need to close all open PairDrop tabs. Only then the service worker / browser will update the cached files in the background and everything should work smoothly again.

Could you please try that and report back whether it worked?
