### ISSUE TITLE
[Bug] link with parameters not working (parameters after = cut off)

### ISSUE THREAD

**Issue by ueen** [schlagmichdoch/PairDrop#231]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Bug occurs on official PairDrop instance https://pairdrop.net/**
No | Yes
Version: v1.10.2

**Bug occurs on self-hosted PairDrop instance**
No | Yes

**Self-Hosted Setup**
Proxy: Nginx | Apache2
Deployment: docker run | docker compose | npm run start:prod
Version: v1.10.2

**Additional context**

**Comment by schlagmichdoch** [comment]
I do not know what you mean. Please fill out the  bug issue template and provide an example

**Comment by ueen** [comment]
Just send this link (invalid) and try to click on it on the recieving end ;)
`
https://onedrive.live.com/?authkey=%dfdsssdf7LJSM3w&id=88ADFF5%21285&cid=2DC78C46388A4354`

**Comment by schlagmichdoch** [comment]
Thanks for the example!

Your title leaves multiple options:
- Sending links via send message dialog does not work properly
- Sending links via Android Share Menu does not work properly
- Sending links via iOS shortcut does not work properly
- Sending links via CLI does not work properly
- etc.
- Sending links does work properly but the links are not correctly converted to clickable links (the actual case)

Adding some general information and a step by step guide how to reproduce the issue makes it much easier to determine whats wrong. This repo is quite easy to maintain but on other repos you might not have gotten an answer in the first place.

This is an issue though. I did some testing:
This message:
```text
www.test
www.test.com
https://test.com
http://test.com
https://test.com?auth=token&si=123
https://onedrive.live.com/?authkey=%dfdsssdf7LJSM3w&id=88ADFF5%21285&cid=2DC78C46388A4354
```
is converted to this html:
```html
<div id="text" class="textarea"><a href="www.test" target="_blank">www.test</a><br><a href="www.test.com" target="_blank">www.test.com</a><br><a href="https://test.com" target="_blank">https://test.com</a><br><a href="http://test.com" target="_blank">http://test.com</a><br><a href="https://test.com?auth=token&amp;si=123" target="_blank">https://test.com?auth=token&amp;si=123</a><br><a href="https://onedrive.live.com/?authkey=" target="_blank">https://onedrive.live.com/?authkey=</a>%dfdsssdf7LJSM3w&amp;id=88ADFF5%21285&amp;cid=2DC78C46388A4354</div>
```

Apparently, the URL replacement does not stop at the equal sign but at the percentage sign.
Also, `www.test.com` should be replaced with `http:/www.test.com` to prevent pointing https://pairdrop.net/www.test.com to and `www.test` should not be a URL at all.

**Comment by ueen** [comment]
ok lets fix it :))

**Comment by schlagmichdoch** [comment]
> maybe this? https://www.freecodecamp.org/news/how-to-validate-urls-in-javascript/
> 
> ```
> try {
>    let url = new URL(message);
>     //set as link
> } catch (err) {
>     //set as text
> }
> ```

Not quite, as we don’t know yet where possible URLs are positioned. Instead, I used a REGEX substitution for this and enhanced it to fix this issue.
See https://github.com/schlagmichdoch/PairDrop/blob/ccb2170287cc47cccf80e576b5d1fb1d986edb26/public/scripts/ui.js#L2018-L2033

**Comment by schlagmichdoch** [comment]
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

Thanks for the example!

Your title leaves multiple options:
- Sending links via send message dialog does not work properly
- Sending links via Android Share Menu does not work properly
- Sending links via iOS shortcut does not work properly
- Sending links via CLI does not work properly
- etc.
- Sending links does work properly but the links are not correctly converted to clickable links (the actual case)

Adding some general information and a step by step guide how to reproduce the issue makes it much easier to determine whats wrong. This repo is quite easy to maintain but on other repos you might not have gotten an answer in the first place.

This is an issue though. I did some testing:
This message:
```text
www.test
www.test.com
https://test.com
http://test.com
https://test.com?auth=token&si=123
https://onedrive.live.com/?authkey=%dfdsssdf7LJSM3w&id=88ADFF5%21285&cid=2DC78C46388A4354
```
is converted to this html:
```html
<a href="www.test" target="_blank">www.test</a><br>
<a href="www.test.com" target="_blank">www.test.com</a><br>
<a href="https://test.com" target="_blank">https://test.com</a><br>
<a href="http://test.com" target="_blank">http://test.com</a><br>
<a href="https://test.com?auth=token&amp;si=123" target="_blank">https://test.com?auth=token&amp;si=123</a><br>
<a href="https://onedrive.live.com/?authkey=" target="_blank">https://onedrive.live.com/?authkey=</a>%dfdsssdf7LJSM3w&amp;id=88ADFF5%21285&amp;cid=2DC78C46388A4354
```

Apparently, the URL replacement does not stop at the equal sign but at the percentage sign.
Also, `www.test.com` should be replaced with `http:/www.test.com` to prevent pointing https://pairdrop.net/www.test.com to and `www.test` should not be a URL at all.

Comment by @schlagmichdoch:
---

> maybe this? https://www.freecodecamp.org/news/how-to-validate-urls-in-javascript/
> 
> ```
> try {
>    let url = new URL(message);
>     //set as link
> } catch (err) {
>     //set as text
> }
> ```

Not quite, as we don’t know yet where possible URLs are positioned. Instead, I used a REGEX substitution for this and enhanced it to fix this issue.
See https://github.com/schlagmichdoch/PairDrop/blob/ccb2170287cc47cccf80e576b5d1fb1d986edb26/public/scripts/ui.js#L2018-L2033
