### ISSUE TITLE
[Query] How to enable send with PairDrop option?

### ISSUE THREAD

**Issue by onlytanmoy** [schlagmichdoch/PairDrop#236]
Hi, happy new year wishes.
qq: when I unzip the recently released pairdrop-cli.zip file I can see 5 files inside that - which one I am supposed to execute in my Windows machine to get 'send with PairDrop' option in the context menu of the files please?

**Comment by schlagmichdoch** [comment]
Happy new years to you too!

On Windows, you need to follow this guide:
https://github.com/schlagmichdoch/PairDrop/blob/master/docs/how-to.md#send-multiple-files-and-directories-directly-from-context-menu-on-windows

If this is not clear enough, I might add some screenshots to it.

**Comment by onlytanmoy** [comment]
@schlagmichdoch Thanks for the guide, I followed the steps there, getting the below error, any fix for that please?

![image](https://github.com/schlagmichdoch/PairDrop/assets/48493659/fb49120e-abb6-472e-a06c-812108ae1344)

**Comment by schlagmichdoch** [comment]
Seems like you (or the Git bash) don’t have permissions to write to `C:/Program Files/pairdrop-cli/`.

Please try two solutions:
1. Add a new file `C:/Program Files/pairdrop-cli/.pairdrop-cli-config` to the same folder with the following content: `DOMAIN=https://pairdrop.net/`
2. Use another folder e.g. `C:/Users/<user>/pairdrop-cli/` for steps 2 and 6

If solution 1 is working I will simply add the config file to the release folder as default.

**Comment by onlytanmoy** [comment]
@schlagmichdoch thanks a lot mate, solution 1 worked like a charm :)
Just a quick query: even though I have PairDrop installed as a PWA from Chrome, while sending a file using this send to context menu it is not launching instead my Chrome browser is being opened for completing the send operation. I suppose that is how it is supposed to work and you cannot send via the PWA?

**Comment by schlagmichdoch** [comment]
Great! Glad it works! :)

Yes this I how it is supposed to work for now. There is a PWA flag in the manifest file to use the existing client, but it is not yet implemented into browsers.
This is the best solution for now. We will only have more control after implementing native clients.

**Comment by onlytanmoy** [comment]
Thanks for the clarification mate.

Can I quickly check if you have any plan to implement PairDrop as a Chrome extension so that I can achieve the following from my laptop to phone
a. Share some copied text from a site
b. Send the URL address
c. Send any raw text

I can then bid farewell to the Pushbullet extension haha

Or if you are aware of any good chrome extension for the above tasks you can share with me that as well.

**Comment by schlagmichdoch** [comment]
I'll close this as it is fixed in the new version `v1.10.5` [1] alongside enhanced documentation [2].

[1] https://github.com/schlagmichdoch/PairDrop/releases/
[2] https://github.com/schlagmichdoch/PairDrop/blob/master/docs/how-to.md




> Can I quickly check if you have any plan to implement PairDrop as a Chrome extension so that I can achieve the following from my laptop to phone
> a. Share some copied text from a site
> b. Send the URL address
> c. Send any raw text

I have no plan to implement this yet. This is a nice idea though so I would appreciate if you would add a new issue for this for anyone to pick up

There is also a Firefox Extension that does something similar and should be compatible with PairDrop: 
Store:
https://addons.mozilla.org/en-US/firefox/addon/snapdrop-for-firefox/

Repo:
https://github.com/ueen/SnapdropFirefoxAddon

Maybe its developer @ueen is interested in implementing this as a Chrome Extension as well.

**Comment by onlytanmoy** [comment]
Done

https://github.com/schlagmichdoch/PairDrop/issues/238

https://github.com/ueen/SnapdropFirefoxAddon/issues/28

**Comment by schlagmichdoch** [comment]
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

Happy new year to you too!

On Windows, you need to follow this guide:
https://github.com/schlagmichdoch/PairDrop/blob/master/docs/how-to.md#send-multiple-files-and-directories-directly-from-context-menu-on-windows

If this is not clear enough, I might add some screenshots to it.

Comment by @schlagmichdoch:
---

Seems like you (or the Git bash) don’t have permissions to write to `C:/Program Files/pairdrop-cli/`.

Please try two solutions:
1. Add a new file `C:/Program Files/pairdrop-cli/.pairdrop-cli-config` to the same folder with the following content: `DOMAIN=https://pairdrop.net/`
2. Use another folder e.g. `C:/Users/<user>/pairdrop-cli/` for steps 2 and 6

If solution 1 is working I will simply add the config file to the release folder as default.

Comment by @schlagmichdoch:
---

I'll close this as it is fixed in the new version `v1.10.5` [1] alongside enhanced documentation [2].

[1] https://github.com/schlagmichdoch/PairDrop/releases/
[2] https://github.com/schlagmichdoch/PairDrop/blob/master/docs/how-to.md




> Can I quickly check if you have any plan to implement PairDrop as a Chrome extension so that I can achieve the following from my laptop to phone
> a. Share some copied text from a site
> b. Send the URL address
> c. Send any raw text

I have no plan to implement this yet. This is a nice idea though so I would appreciate if you would add a new issue for this for anyone to pick up

There is also a Firefox Extension that does something similar and should be compatible with PairDrop: 
Store:
https://addons.mozilla.org/en-US/firefox/addon/snapdrop-for-firefox/

Repo:
https://github.com/ueen/SnapdropFirefoxAddon

Maybe its developer @ueen is interested in implementing this as a Chrome Extension as well.
