### ISSUE TITLE
Bug: You need to be online to pair devices.

### ISSUE THREAD

**Issue by niklaskoskowski** [schlagmichdoch/PairDrop#24]
Hi there, 
i just set up PairDrop on my netcup.de Webhosting via node.js.
So far so good, but as soon as I try to use it, it either says "No server connection. Retry in 5s..." or "You need to be online to pair devices."

**Comment by schlagmichdoch** [comment]
This probably happens because your HTTP server does not route your websocket requests correctly. Therefore, those requests fail and the client shows a message that the server is not reachable.

Be sure to follow the documention and have a look at the Apache configuration example: https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#using-apache
specifically:
```conf
	RewriteEngine on
	RewriteCond %{HTTP:Upgrade} websocket [NC]
	RewriteCond %{HTTP:Connection} upgrade [NC]
	RewriteRule ^/?(.*) "wws://127.0.0.1:3000/$1" [P,L]
```

**Comment by schlagmichdoch** [comment]
@niklaskoskowski Has it worked since? I’d like to close this issue.

**Comment by schlagmichdoch** [comment]
@niklaskoskowski I will close this for now. Feel free to reopen with additional information if it is still not working for you.

**Comment by infocillasas** [comment]
Hi @schlagmichdoch 
I'm experiencing issues related to this topic. Frontend app is OK, I can pair some devices on the same network but devices don't show when I just land on the homepage. It works perfectly on pairdrop.net.

I suppose there is something to do with my apache proxy.

My Setup: selhosted on a bare metal Debian server with Docker (I intentionnaly disactivated the coturn part, is that OK)
The host port is 3082 as the port 3000 is already used. Here the section of the docker-compose file:
```
ports:
      - "127.0.0.1:3082:3000"
```

My apache config looks like this:
```
<VirtualHost *:80>
   ServerName mydomain

Redirect permanent / https://mydomain/

</VirtualHost>

<VirtualHost *:443>
   ServerName mydomain

ProxyPass / http://127.0.0.1:3082/

RewriteEngine On
RewriteCond %{HTTP:Upgrade} webso#and then the ssl partcket [NC]
RewriteCond %{HTTP:Connection} upgrade [NC]
RewriteRule ^/?(.*) "ws://127.0.0.1:3082/$1" [P,L]

SSLCertificateFile /etc/letsencrypt/live/xxx.pem
SSLCertificateKeyFile /etc/letsencrypt/live/xxx.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
```

It doesn't work if I put "https" in the ProxyPass section as mentionned in the documentation (lots of ssl errors in apache's logs) and also if I put "wws://" in the websocket section of the apache config, it doesn't work.

With the above setup it works but devices on the same network are not detected automatically. I can force the pairing with the 6 digits code, that's it.

Could you help me ?

Another issue is that the coturn docker container doesn't start up correctly. It continuously starts (see screenshot below)

![image](https://github.com/schlagmichdoch/PairDrop/assets/150066394/c5812e45-c820-4aa1-9633-281e357717f5)

**Comment by DerSaxxe** [comment]
Sorry for reopen... But I have the same problem like @niklaskoskowski with webhosting 8000 at netcup. PairDrop installation runs fine with node.js in plesk and I can see my own PairDrop website. But pairing or joining room ends in "You need to be online to create a public room /  to pair devices". I don't have much access to apache config because of webhosting, is there another solution?
