### ISSUE TITLE
PairDrop on Firefox for iOS hangs on Loading [Bug] 

### ISSUE THREAD

**Issue by manek43509** [schlagmichdoch/PairDrop#246]
**Describe the bug**
When I try to use Pairdrop on the Firefox browser on my iPhone, the 'You are known as' field hangs on 'Loading' and never assigns a handle. The iPhone therefore doesn't show up on any other connected devices.

**To Reproduce**
1. Go to pairdrop.net using Firefox on an iPhone.

**Screenshots**
![IMG_0898](https://github.com/schlagmichdoch/PairDrop/assets/124011743/a4a87b90-7e23-48bc-b018-1f6acc383044)

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS15.7
 - Browser: Firefox for iOS
 - Version: latest

**Bug occurs on official PairDrop instance https://pairdrop.net/**
Yes
Version: v1.10.5

**Bug occurs on self-hosted PairDrop instance**
No

**Comment by schlagmichdoch** [comment]
This might be related to #243 .
Please verify that the issue is not present on this instance:
https://pairdrop-dev.onrender.com/

**Comment by manek43509** [comment]
Yes, that seems to work (although I haven’t tried sending anything to another device, as I’m out right now and I only have my phone on me).

**Comment by gessha** [comment]
I had the same problem on iPad Pro (3rd generation) on iPadOS 16.2 I got fixed when I updated to 17.2

**Comment by schlagmichdoch** [comment]
Thanks @manek43509 and @gessha for testing! That supports the thesis that it’s related to a not supported feature in older iOS / MacOS Safari versions. I’ll merge this later and release a new version.

**Comment by schlagmichdoch** [comment]
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

This might be related to #243 .
Please verify that the issue is not present on this instance:
https://pairdrop-dev.onrender.com/
