### ISSUE TITLE
[Bug] Copying message via button fails using HONOR browser

### ISSUE THREAD

**Issue by Issac-Lee** [schlagmichdoch/PairDrop#250]
**Describe the bug**
I sent a message on my Mac, but it can't be copied on my phone by the copy-icon. I need to select the whole message, long click them to copy. But I sent message from my phone to Mac, I can copy it by click copy-icon.

**Comment by Issac-Lee** [comment]
> What kind of phone and browser are you using? Please always include the data of the template in your issues.

Phone: Honor magic 5 pro, system is its own magicOS 8.0 based on android 14
browser: Safari on MacBook Air

**Comment by schlagmichdoch** [comment]
Thanks! What browser do you use on the phone? Have you tried using another browser?

**Comment by Issac-Lee** [comment]
> Thanks! What browser do you use on the phone? Have you tried using another browser?

I usually use its own browser in system. I tried another browser and edge browser for android works.

**Comment by schlagmichdoch** [comment]
I could not find a lot about the HONOR browser. As it is based on the Huawei Browser I believe some APIs are simply not implemented.
Have a look at caniuse.com for other browsers that support the api:
https://caniuse.com/async-clipboard

Also, does PairDrop give you a warning message when the copying does not work? What would be your preferred fallback solution?

**Comment by Issac-Lee** [comment]
> I could not find a lot about the HONOR browser. As it is based on the Huawei Browser I believe some APIs are simply not implemented. Have a look at caniuse.com for other browsers that support the api: https://caniuse.com/async-clipboard

Thanks a lot

> Also, does PairDrop give you a warning message when the copying does not work? What would be your preferred fallback solution?

yes, it gives me a guide that u need to copy messages by select all the words. At the end, I choose google chrome as default browser and everything's ok.

**Comment by schlagmichdoch** [comment]
Thanks for your feedback! I’ll close this.

**Comment by schlagmichdoch** [comment]
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

I could not find a lot about the HONOR browser. As it is based on the Huawei Browser I believe some APIs are simply not implemented.
Have a look at caniuse.com for other browsers that support the api:
https://caniuse.com/async-clipboard

Also, does PairDrop give you a warning message when the copying does not work? What would be your preferred fallback solution?
