### ISSUE TITLE
[Enhancement] Option: do not zip files and send them all individually

### ISSUE THREAD

**Issue by mteomi** [schlagmichdoch/PairDrop#287]
**What problem is solved by the new feature**
When I send files they get zipped, I've noticed most file transfer services tend to zip all the files togheter, but sometimes it's more comfortable to just get the files like if you are downloading a torrent, in order to save time

**Describe the feature**
The "Do not zip files and send them all individually" option would be a feature that not only makes possible to send files separately but tu directly upload folders and send them to the other peer, which, again, saves time, and space, since when you unzip a file, you need the space taken by the compressed file, plus the space for the files that are getting decompressed, hence taking twice the space and time to zip and unzip

**Comment by schlagmichdoch** [comment]
Files are already sent individually and only zipped on the receiving device. This is only done on desktop clients, as on Android and iOS the Share Menu is used.

The UX is currently under development.
There is an ongoing discussion to give users on desktop clients the choice to download the files individually instead of creating an archive and downloading that. Feel free to add your thoughts over here:
https://github.com/schlagmichdoch/PairDrop/issues/40#issuecomment-2010347771
