### ISSUE TITLE
Add explanation

### ISSUE THREAD

**Issue by Myzel394** [schlagmichdoch/PairDrop#3]
Hey, first of all: GREAT PROJECT! I really wanted to see a pairing functionality on Snapdrop and it's really cool to see it implemented finally! I'm currently trying to figure out how it works and thought maybe it'd be nice for new people to see kind of how this all works. Could you create some kind of flow chart on how PairDrop works on a high level or explain it in text? I'd be really interested in learning it :)

**Comment by schlagmichdoch** [comment]
Exacltly! Encryption is mandatory for WebRTC connections and completely done by the browser itself. Implementing any encryption by yourself is always a bad idea ;)

When the peers are first connecting, a channel is created by exchanging their signaling information. This signaling information includes some sort of public key and is specific to the clients ip address. That is what the STUN Server is used for: it simply returns your public IP address as you only know your local ip address if behind a NAT (router).

The transfer of the signaling information is done by the PairDrop / Snapdrop server using secure websockets.
After that the channel itself is completely peer-2-peer and all information can only be decrypted by the receiver.
When the two peers are on the same network or when they are not behind any NAT system (which they always are for classic Snapdrop and for not paired users on PairDrop) the files are send directly peer to peer.

When a user is behind a NAT (behind a router) the contents are channeled through a TURN server. But again, the contents send via the channel can only be decrypted by the receiver. So a rogue TURN server could only see that there is a connection, but not what is send. Obviously, connections which are channeled through a TURN server are not as fast as peer to peer.

The selection whether a TURN server is needed or not is also done automatically by the browser. It simply iterated through the configured RTC iceServers and checks what works. Only if the STUN server is not sufficient, the TURN server is used.

![img](https://www.wowza.com/wp-content/uploads/WeRTC-Encryption-Diagrams-01.jpg)

Good thing: if your device has a IPv6 address it is uniquely reachable by that address. As I understand it, when both devices are using IPv6 addresses there is no need for a TURN server in any scenario.

To learn more take a look at https://www.wowza.com/blog/webrtc-encryption-and-security which gives a good insight into stun, turn and webrtc

---

The pairing functionality is classic webdev and works by using the [IndexedDB API](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API).

It works by creating long secrets that are served by the server to the initiating and requesting pair peer, when the inserted key is correct. These long secrets are then saved to a IndexedDB database in the browser. IndexedDB is somewhat the successor of localStorage as saved data is shared between all tabs. It goes one step further by making the data persistent and available offline if implemented to a PWA.

All secrets a client has saved to its database are send to the PairDrop server. Peers with a common secret are discoverable to each other analog to peers with the same ip-address are discoverable to each other.

What I really like about this approach, and the reason why I implemented it, is, that devices on the same network are always visible no matter whether any devices are paired or not. The main user flow is never obstructed. Paired devices are simply shown additionally. This makes it in my idea superior to the idea of switching rooms like on https://www.wulingate.com/en/

**Comment by Myzel394** [comment]
Thank you very much for this detailed explanation! I'm gonna take a deep look at it :D One simple question: How did you create this figure? Did you use Figma or is there a special tool for such things available?

**Comment by schlagmichdoch** [comment]
I added a link to the technical documention [to the FAQ](https://github.com/schlagmichdoch/pairdrop/blob/master/docs/faq.md#how-does-it-work). Does this close your issue?

I did not ;)
The figure is taken from the link I referenced but if I had to do it I would probably take [Lucidchart](https://www.lucidchart.com/)

**Comment by schlagmichdoch** [comment]
I'll close this for now. If you need any further information feel free to reopen this issue!

**Comment by schlagmichdoch** [comment]
The following comments were deleted by hubot as part of [mistakenly marking this account as spam on 17th February 2024](#284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to preserve the information they hold:

Comment by @schlagmichdoch:
---

Congratulations! You found this project even before I finished implementing it ;)

The pairing functionality was my primary drive to extend snapdrop myself, as I did not see that coming in the original snapdrop repository.
But while at it, I also implemented ways to send files directly from share-menus and windows context menus. This is all working now and is live at https://pairdrop.net! 🎉 

What's left is to improve the documentation (as always ;) ) so thank's for your issue! I guess I will add a how-it-works.md to explain the technical background further than currently [in the faq](https://github.com/schlagmichdoch/pairdrop/blob/master/docs/faq.md#what-about-the-connection-is-it-a-p2p-connection-directly-from-device-to-device-or-is-there-any-third-party-server).

As you are the first, I have some questions to you:
- What exactly are you looking for in the documentation?
- What parts are you interested in most? 
- Is the FAQ sufficient for you or would you like to see some graphs?
- Which function should be documented?

Comment by @schlagmichdoch:
---

Exacltly! Encryption is mandatory for WebRTC connections and completely done by the browser itself. Implementing any encryption by yourself is always a bad idea ;)

When the peers are first connecting, a channel is created by exchanging their signaling information. This signaling information includes some sort of public key and is specific to the clients ip address. That is what the STUN Server is used for: it simply returns your public IP address as you only know your local ip address if behind a NAT (router).

The transfer of the signaling information is done by the PairDrop / Snapdrop server using secure websockets.
After that the channel itself is completely peer-2-peer and all information can only be decrypted by the receiver.
When the two peers are on the same network or when they are not behind any NAT system (which they always are for classic Snapdrop and for not paired users on PairDrop) the files are send directly peer to peer.

When a user is behind a NAT (behind a router) the contents are channeled through a TURN server. But again, the contents send via the channel can only be decrypted by the receiver. So a rogue TURN server could only see that there is a connection, but not what is send. Obviously, connections which are channeled through a TURN server are not as fast as peer to peer.

The selection whether a TURN server is needed or not is also done automatically by the browser. It simply iterated through the configured RTC iceServers and checks what works. Only if the STUN server is not sufficient, the TURN server is used.

![img](https://www.wowza.com/wp-content/uploads/WeRTC-Encryption-Diagrams-01.jpg)

Good thing: if your device has a IPv6 address it is uniquely reachable by that address. As I understand it, when both devices are using IPv6 addresses there is no need for a TURN server in any scenario.

To learn more take a look at https://www.wowza.com/blog/webrtc-encryption-and-security which gives a good insight into stun, turn and webrtc

---

The pairing functionality is classic webdev and works by using the [IndexedDB API](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API).

It works by creating long secrets that are served by the server to the initiating and requesting pair peer, when the inserted key is correct. These long secrets are then saved to a IndexedDB database in the browser. IndexedDB is somewhat the successor of localStorage as saved data is shared between all tabs. It goes one step further by making the data persistent and available offline if implemented to a PWA.

All secrets a client has saved to its database are send to the PairDrop server. Peers with a common secret are discoverable to each other analog to peers with the same ip-address are discoverable to each other.

What I really like about this approach, and the reason why I implemented it, is that devices on the same network are always visible no matter whether any devices are paired or not. The main user flow is never obstructed. Paired devices are simply shown additionally. This makes it in my opinion superior to the idea of switching rooms like on https://www.wulingate.com/en/
