### ISSUE TITLE
[Feature Request] Add an authentication page

### ISSUE THREAD

**Issue by AzamServer** [schlagmichdoch/PairDrop#54]
Is there anyway you could add an authentication page that people would have to login to in order to share files? Below are a few things you could implement.

- Authentication (username and password)
- Disable or enable authentication in the docker environment variables
- Disable or enable new user registration in the docker environment variables
- 2FA (FIDO2 or TOTP)

Love the project by the way!

**Comment by schlagmichdoch** [comment]
Glad you like it!

One goal of the project is to make it easy and straightforward for everyone to share files. What’s your use for authentication? What problem do you face when others can use your instance too?

I don’t want to obstruct the main user flow in any way.

**Comment by AzamServer** [comment]
> Glad you like it!
Thanks!

> One goal of the project is to make it easy and straightforward for everyone to share files. What’s your use for authentication? What problem do you face when others can use your instance too?
Sometimes I use my instance of Pairdrop on school Wi-Fi where a lot of people (especially those within my computer science courses) know my domain. I don't want them to open pairdrop and accidentally receive my code or abuse my instance of pairdrop.

> I don’t want to obstruct the main user flow in any way.
I don't believe this would obstruct the general user interface as only those who enable authentication should have it, so if it's there, someone wanted it, so it's not an obstruction to them.

**Comment by schlagmichdoch** [comment]
I guess the best approach for you would be to add authentication directly to your proxy server:
https://mrgood.blog/posts/2021-03-11-apache-auth/post.html
This would require username + password for every new session. This is better done on the server level than as a feature of PairDrop.

> accidentally receive my code

What do you mean with that?

**Comment by schlagmichdoch** [comment]
I will close this as answered and `wontfix`

**Comment by schlagmichdoch** [comment]
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

I guess the best approach for you would be to add authentication directly to your proxy server:
https://mrgood.blog/posts/2021-03-11-apache-auth/post.html
This would require username + password for every new session. This is better done on the server level than as a feature of PairDrop.

> accidentally receive my code

What do you mean with that?
