### ISSUE TITLE
Enhancement: How to change the display name?

### ISSUE THREAD

**Issue by DennisGaida** [schlagmichdoch/PairDrop#61]
It says in the readme: *Change your display name permanently to easily differentiate your devices*

I have tried multiple things like right-clicking, searching through the code, clicking on several button but I just don't know how to change the display name of the current device (or any paired device).

How do I change my display name and maybe also add this to the FAQ / readme, thank you!

**Comment by schlagmichdoch** [comment]
Hi @DennisGaida,

Sorry for the confusion! Renaming is not live yet.

I recognized an important stability issue with the current implementation of the renaming feature after merging it into the master but before releasing and pulling it onto pairdrop.net yesterday. I will resolve this later today and come back to you!

**Comment by schlagmichdoch** [comment]
it's live now🥊

**Comment by schlagmichdoch** [comment]
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

Hi @DennisGaida,

Sorry for the confusion! Renaming is not live yet.

I recognized an important stability issue with the current implementation of the renaming feature after merging it into the master but before releasing and pulling it onto pairdrop.net yesterday. I will resolve this later today and come back to you!
