### ISSUE TITLE
File sent successfully but not displayed

### ISSUE THREAD

**Issue by pdxadp** [schlagmichdoch/PairDrop#76]
I use Mac Chrome to send a large file to iPhone Safari, and it shows that it has been successfully sent, but iPhone Safari does not give any prompts. Normally, the sharing menu will appear, but it does not appear.
Tried many times, all failed.
Sending small files works fine.

**Comment by pdxadp** [comment]
> How big of a file do we talk about? Requests _to_ an iPhone should be denied automatically if the file is above 200 MB as iOS Safari crashes if to much RAM is used

80MB video file
Sending that file from iPhone to Mac works fine

**Comment by pdxadp** [comment]
I think this may be a bug of iPhone Safari, the share menu does not appear every time, even if I send a 1MB photo, sometimes the share menu does not appear

**Comment by schlagmichdoch** [comment]
Is it only the iOS share-menu that is not opened but PairDrop opens the `Image Received` dialog? 

If the transfer takes a while the share-menu cannot be automatically opened as it requires an active user interaction. Tapping on `Share` should work however.

**Comment by schlagmichdoch** [comment]
I could reproduce your issue and justed fixed it. Somehow the file preview did not work properly on big files on iOS. The 'File received' dialog is now shown independently from the preview being loaded. The fix is now live on pairdrop.net

**Comment by schlagmichdoch** [comment]
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

Is it only the iOS share-menu that is not opened but PairDrop opens the `Image Received` dialog? 

If the transfer takes a while the share-menu cannot be automatically opened as it requires an active user interaction. Tapping on `Share` should work however.

Comment by @schlagmichdoch:
---

I could reproduce your issue and justed fixed it. Somehow the file preview did not work properly on big files on iOS. The 'File received' dialog is now shown independently from the preview being loaded. The fix is now live on pairdrop.net
