### ISSUE TITLE
Bug:Does not work properly in some browsers

### ISSUE THREAD

**Issue by pdxadp** [schlagmichdoch/PairDrop#79]
I use Chrome on an Android phone, and I have been unable to enter PairDrop normally (the name and other devices are not displayed), the problem persists after reinstalling Chrome, and the screenshot shows the error provided by the debugging tool.

The same browser can normally access and use the services built by Snapdrop. So the browser should be fine.

Oddly, another Android phone works fine.

**Screenshots**
<img width="807" alt="CleanShot 2023-03-13 at 13 26 08@2x" src="https://user-images.githubusercontent.com/36809596/224615149-925fd1f1-1db1-4ce5-8f65-51f2ce1a323a.png">

**Self-Hosted**
No

**Comment by schlagmichdoch** [comment]
Thanks for your issue!
What phone, Android, and Chrome version are you using?

**Comment by pdxadp** [comment]
Phone:SAMSUNG A13
Android 13
Chrome 78.0.3904.96
Only pairdrop cannot be used normally

**Comment by schlagmichdoch** [comment]
@pdxadp The changes are currently live on the dev instance: https://pairdrop-dev.onrender.com/
Could you please test it and give feedback whether this would solve your issue?

**Comment by pdxadp** [comment]
> 



> @pdxadp The changes are currently live on the dev instance: https://pairdrop-dev.onrender.com/ Could you please test it and give feedback whether this would solve your issue?

I tested the site you provided on that android phone and it works fine!👍🏻

**Comment by schlagmichdoch** [comment]
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

@pdxadp The changes are currently live on the dev instance: https://pairdrop-dev.onrender.com/
Could you please test it and give feedback whether this would solve your issue?
