### ISSUE TITLE
Question/Bug: Is there a way within iOS to make it save photos to the photo library?

### ISSUE THREAD

**Issue by jschwalbe** [schlagmichdoch/PairDrop#84]
**Describe the bug**
I don't see a way to save photos to the photo library. It's confusing/frustrating since the actual built in AirDrop on iOS does allow this (seems to be the default option).

**To Reproduce**
1. Load website on iOS device
2. Send photo from another (iOS) device

**Expected behavior**
Should have an option to import to Photo Library

**Desktop (please complete the following information):**
- iOS

**Smartphone (please complete the following information):**
 - iOS 16.3.1
 - Browser Chrome

**Self-Hosted**
Yes

**Self-Hosted Setup**
docker compose

**Comment by jschwalbe** [comment]
Yep! Thanks & sorry I didn’t see it.

**Comment by schlagmichdoch** [comment]
No worries! I will try to make the faq more visible

**Comment by jschwalbe** [comment]
Unrelated to this issue but since we’re active here, I also noticed that the linked docker compose file is different than the text elsewhere (in the readme?). Sorry I’m on mobile.

**Comment by schlagmichdoch** [comment]
I‘m not sure what you mean exactly, but I’l try to explain the differences: There are many possible ways to host your own instance. The docker-compose file in this repo can be used if you want to build your own image from the files in this repo. The given docker-compose file in the host-your-own.md can be used if you want to get the image from docker hub without any git cloning. Same with the Dockerfile.

**Comment by jschwalbe** [comment]
That makes more sense! Took me a bit to figure out the docker hub part of it. Thanks

**Comment by schlagmichdoch** [comment]
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

Does this answer your question?

https://github.com/schlagmichdoch/PairDrop/blob/master/docs/faq.md#when-i-receive-images-on-ios-i-cannot-add-them-directly-to-the-gallery
