### ISSUE TITLE
Feature Request: Reset theme toggle to auto

### ISSUE THREAD

**Issue by schlagmichdoch** [schlagmichdoch/PairDrop#85]
After toggling the theme button there is no way of setting it back to use the system default.

I imagine sth like, if the current theme is equal to the saved theme clicking the toggle again resets the theme back to system default by deleting the localStorage entry.

Not sure whether there should be a moon logo with (auto) attached whenever no theme is set or a user notification („Theme is now set by the system automatically“) when changed back to auto.

Pinging @Bellisario as I’ve seen, that you have thought about this issue already for Snapdrop

**Comment by Bellisario** [comment]
@schlagmichdoch, thanks for pinging me!

Yes, I have some implementation examples:

- long pressing to reset theme (but now re-thinking this could not be a good solution because the command is "hidden"
- a menu to "choose your look" (the option I like the most)
- a triple switch to choose from "Auto", "Light" and "Dark" switching on right or left depending option to set and default "Auto" (this could be cool but difficult to manage for different browsers and mobile devices)

---

Talking about the "choose your look" menu, I like the idea to display something like macOS:

![macOS "choose your look"](https://user-images.githubusercontent.com/72039923/225044837-2bd7b7da-b660-47e6-9448-0bb438625722.png)

I also shown a dialog example (without some kind of theme preview):

![dialog preview](https://user-images.githubusercontent.com/72039923/225045383-6261dce9-972b-4208-b85c-48a2ed095045.png)

> Not sure this is the best solution but seems an "Apple" touch for Pairdrop, which already re-implements a bit of AirDrop UI from Apple itself.

**Comment by schlagmichdoch** [comment]
Thanks for the quick input!

I think a new dialog would make the switch more complicated for the user.

> * a triple switch to choose from "Auto", "Light" and "Dark" switching on right or left depending option to set and default "Auto" (this could be cool but difficult to manage for different browsers and mobile devices)

If we did that, would you prefer a logo change with `auto` or a user-notification that the system default is used now?

**Comment by Bellisario** [comment]
> If we did that, would you prefer a logo change with `auto` or a user-notification that the system default is used now?

I think a logo change would be the right solution.

>  Maybe also sth like on the bottom of this page: https://www.linuxserver.io/

Yes, this could be a solution, but I need to warn you it's really difficult to apply custom styles on `select` elements, [see here](https://moderncss.dev/custom-select-styles-with-pure-css/).

My suggestion is to make something like this (without using the built-in `select` element):

![image](https://user-images.githubusercontent.com/72039923/225380922-749a972e-7f55-4a69-9f63-2e34002f7ae7.png)

> Of course then we could make the icon (the main icon to click to change mode) reactive to the theme (ex. if dark mode is default we'll show its icon and selection options "auto" and "light").

**Comment by schlagmichdoch** [comment]
I like that idea!
I will play around a little and come back to you. Probably I will try to open the little menu on mouse hover or click to ensure only one click is needed on desktop to change the theme.
I’m not sure about the icon order though.
Should it always be the same order (auto, light, dark) or should the opposite theme always be on top to preserve the current behavior of switching on click?

**Comment by schlagmichdoch** [comment]
Found a compromise of your two solutions I'm happy with.

It works like a hover menu on desktop and a three-option toggle on mobile.

Could you please test it at https://pairdrop-dev.onrender.com/ before I merge it? :)

**Comment by Bellisario** [comment]
Wow, beautiful!
Love also the transition that changes the icon displayed by default!

---

Just not very sure about the mobile version: it shows on fist tap the dark mode, then comes back to light mode and back again to auto mode (why this behavior?!?!).

https://user-images.githubusercontent.com/72039923/228335048-55479379-0c03-4b04-95e0-dfcefe17db4b.mp4

Also, on mobile I would first show the currently active theme (ex. dark mode auto => dark mode on fist tap) to prevent users to see another theme without further interaction (as "eye-saver"). For example, if using "auto" dark mode, instead of showing light mode next, we show a "fixed" dark mode, while if user is currently in "auto" light mode, we show first light mode and then dark mode.

**Comment by schlagmichdoch** [comment]
Glad you like it! :)

Regarding the mobile version we could switch the toggle order around of course.

I thought about two things:
- Imitating the current behavior: when you enter the page the first time and your system does not provide the dark mode setting, you want to enable it with one tap
- I’m not sure whether it’s weird when tapping it once and nothing changes visible apart from the icon.

That it „comes back“ or moves up again is because I do not ever change the icon order.

So your request means:
- auto dark mode: auto -> dark -> light -> auto
- auto light mode: auto -> light -> dark -> auto

Do you think we should also flip the icon order, so the animation is always from top to bottom or is it better to have the same order on all devices in all situations?

I’m not sure yet what’s best but I lean towards your request.

**Comment by schlagmichdoch** [comment]
So I just updated the mobile view to animate the toggling always from top to bottom by reversing the order on touch devices.

I will keep it that way and won't apply the request. The toggle order is always: auto -> dark -> light -> auto. This means, no matter which mode the browser/system prefers it always switches from auto to dark mode. Only if the dark mode is enabled, the light mode comes up. Okay for you?

**Comment by Bellisario** [comment]
Perfect! With this change of light mode "coming" from bottom instead of top seems better.

**Comment by schlagmichdoch** [comment]
Alright, then I will merge this. Thanks for your help! 🚀
